# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.OpenJDK.25
PackageVersion: 25.0.1.8
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /TASKS="FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome" /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: uninstallPrevious
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://aka.ms/download-jdk/microsoft-jdk-25.0.1-windows-x64.exe
  InstallerSha256: 6AE862D8325BBD7D1A47A99F1C6695A289D581C07E88924D25FCE16D13404A53
  ProductCode: '{9DA4BE12-C58B-3DE4-C047-AF46365065FC}_is1'
  AppsAndFeaturesEntries:
    - ProductCode: '{9DA4BE12-C58B-3DE4-C047-AF46365065FC}_is1'
      InstallerType: inno
    - ProductCode: '{196092C0-357A-4D7A-9893-20C6104EAABA}'
      UpgradeCode: '{9DA4BE12-C58B-3DE4-C047-AF46365065FC}'
      InstallerType: wix
# - Architecture: arm64
#   InstallerUrl: https://aka.ms/download-jdk/microsoft-jdk-25.0.1-windows-aarch64.exe
#   InstallerSha256: 09F2B2938F82040D0564EA953D3E7308278E2B7E6F9476B8B9D09777FD5CCF56
#   AppsAndFeaturesEntries:
#     - DisplayName: "Your Product"
#       Publisher: "Your Company"
#       InstallerType: inno
#     - ProductCode: '{22969A7C-0C72-47F7-AFA7-FC0292F55E10}'
#       InstallerType: wix
ManifestType: installer
ManifestVersion: 1.10.0
